spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_book
      username: root
      password: mysql

  mvc:
    view:
      prefix: /
      suffix: .jsp
      


  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

girl:
  name: dd
  age: 111


#设置spring-boot 编码格式
#banner.charset=UTF-8
#server.tomcat.uri-encoding=UTF-8
#spring.http.encoding.charset=UTF-8
#spring.http.encoding.enabled=false
#spring.http.encoding.force=true
#spring.messages.encoding=UTF-8










